#!/bin/bash

__bootstrap() {
  echo -e ". Bootstrapping Servers..."

  while [[ $# -gt 0 ]] ; do
    server="$1" ; shift
    echo ".. ${server}..."

    ssh ${server} "$bootstrap_sh"
    ssh ${server} "$bootstrap_rvm"
  done

  echo ". Done!"
}

bootstrap_sh='
command -v chef-solo >/dev/null && {
  echo ".. Chef Already Bootsrapped - skipping..."
  exit
}
ohai_version=0.6.10
chef_version=0.10.8

echo ".. Installing Prerequisite Packages ..."
sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get install -y build-essential git-core curl libssl-dev libxslt-dev libxml2-dev libreadline-dev zlib1g-dev
sudo apt-get install -y binutils-doc gcc autoconf flex bison libtool

echo ".. Installing RVM ..."
sudo bash -s stable < <(curl -s https://raw.github.com/wayneeseguin/rvm/master/binscripts/rvm-installer )
source /etc/profile.d/rvm.sh
# (
# cat <<'EOP'
# [[ -s "/usr/local/lib/rvm" ]] && . "/usr/local/lib/rvm"  # This loads RVM into a shell session.
# EOP
# ) > /etc/profile.d/rvm.sh

source /etc/profile

echo ".. Modifying ubuntu user for rvm ..."
sudo usermod -a -G rvm ubuntu

ohai_version=0.6.10
chef_version=0.10.8

echo ".. Installing Ruby 1.9.2 ..."
rvm install 1.9.2
rvm --default 1.9.2
rvm use 1.9.2

echo ".. Installing Chef ..."
gem install -v ${ohai_version} ohai --no-rdoc --no-ri
gem install -v ${chef_version} chef --no-rdoc --no-ri

echo ". /etc/profile.d/rvm.sh"|cat - /etc/skel/.bashrc > /tmp/out && chmod 644 /tmp/out && sudo chown root:root /tmp/out && sudo mv /tmp/out /etc/skel/.bashrc

sudo ln -nsf `command -v chef-solo` /usr/bin/chef-solo
'