#!/bin/bash

__update() {
  echo -e ". Updating Servers..."

  while [[ $# -gt 0 ]] ; do
    server="$1" ; shift
    echo ".. ${server}..."

    server_role=${BASH_REMATCH[1]}
    server_loc=${BASH_REMATCH[2]}
    server_num=${BASH_REMATCH[3]}

    echo ".. Updating Cookbooks..."
    rsync -Caz --delete --exclude .git --rsh='ssh' ./ ${server}:${chef_file_dest}

    echo ".. Running Chef Solo..."
    ssh ${server} "
sudo chmod -R a+w /tmp/chef
source /etc/profile
if command -v rvm >/dev/null; then
 rvmsudo chef-solo -c ${chef_file_dest}/solo-config.rb -j ${chef_file_dest}/dna/${server}.json
else
sudo chef-solo -c ${chef_file_dest}/solo-config.rb -j ${chef_file_dest}/dna/${server}.json
fi
"
  done

  echo ". Done!"
}